### PR TITLE
fix/852-staking-flow-copy-updates

### LINKED ISSUE #852: Copy change for in progress message for removing stake
While removing stake ( at the end of epoch or now) the copy talks about crediting the token which is incorrect

Screenshot 2021-11-16 at 18 32 34

### PR DESCRIPTION
**Pull request by pgriscti**
closes #852

### CODE REVIEW

**Review by dexturr — APPROVED** [review]

**Review by campbellssource — APPROVED** [review]
copy looks good to me

**Comment by dexturr** [comment]
does this want to go to master in light of recent environment changes?

**Comment by dexturr** [comment]
@pgriscti Cypress tests failing due to copy changes can you update the tests when you have a moment :D

**Comment by pgriscti** [comment]
> @pgriscti Cypress tests failing due to copy changes can you update the tests when you have a moment :D

done

**Pull request merged**
